[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/zoho/create-event"
  to = "/.netlify/functions/zoho-create-event"
  status = 200

# Callback OAuth → función serverless
[[redirects]]
  from = "/api/zoho/callback"
  to = "/.netlify/functions/zoho-callback"
  status = 200

# Redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de optimización
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache optimizado para CSS/JS
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para mejor performance
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Link = '''
    <https://fonts.googleapis.com>; rel=preconnect,
    <https://fonts.gstatic.com>; rel=preconnect; crossorigin
    '''